- name: Install PostgreSQL
  ansible.builtin.include_tasks:
    file: install.yml

- name: Configure HAProxy
  ansible.builtin.template:
    src: templates/haproxy.cfg.j2
    dest: "{{ haproxy_config_path }}"
    owner: "{{ proxy_user }}"
    group: "{{ proxy_group }}"
    mode: '0644'

- name: Restart HAProxy
  ansible.builtin.service:
    name: "{{ proxy_user }}"
    state: restarted
    enabled: true