---
- name: Start Haproxy
  # This playbook sets up PostgreSQL, Patroni, and etcd on all hosts.
  hosts: all
  gather_facts: true

  vars_files:
    - vars/main.yml
  tasks:
    - name: Gather EC2 facts
      amazon.aws.ec2_instance_info:
        region: "{{ aws_region }}"
      register: ec2_facts

  roles:
    - common
    - haproxy